-- Tabla principal de turnos
create table if not exists public.appointments (
    id bigint generated by default as identity primary key,
    first_name text not null,
    last_name text not null,
    dni text not null,
    appointment_date date not null,
    appointment_time time not null,
    exams text[] not null default '{}',
    created_at timestamptz not null default now()
);

create index if not exists idx_appointments_date_time
    on public.appointments (appointment_date, appointment_time);

create index if not exists idx_appointments_dni
    on public.appointments (dni);

-- Tabla para resultados en PDF (etapa siguiente)
create table if not exists public.results (
    id bigint generated by default as identity primary key,
    appointment_id bigint not null references public.appointments(id) on delete cascade,
    access_code text not null,
    pdf_path text not null,
    notes text,
    created_at timestamptz not null default now()
);

create index if not exists idx_results_access_code
    on public.results (access_code);

-- Activar RLS
alter table public.appointments enable row level security;
alter table public.results enable row level security;

-- Politicas basicas para demo publica (ajustar para produccion)
drop policy if exists anon_insert_appointments on public.appointments;
create policy anon_insert_appointments
    on public.appointments
    for insert
    to anon
    with check (true);

drop policy if exists anon_select_appointments on public.appointments;
create policy anon_select_appointments
    on public.appointments
    for select
    to anon
    using (true);

drop policy if exists anon_update_appointments on public.appointments;
create policy anon_update_appointments
    on public.appointments
    for update
    to anon
    using (true)
    with check (true);

drop policy if exists anon_delete_appointments on public.appointments;
create policy anon_delete_appointments
    on public.appointments
    for delete
    to anon
    using (true);

-- Politicas de resultados (solo lectura anon para etapa publica)
drop policy if exists anon_select_results on public.results;
create policy anon_select_results
    on public.results
    for select
    to anon
    using (true);

-- Bucket sugerido para PDFs (ejecutar en SQL editor)
insert into storage.buckets (id, name, public)
values ('resultados-pdf', 'resultados-pdf', false)
on conflict (id) do nothing;
